# configs/config.yaml
wandb:
  project: "1st run"

data:
  data_dir: "coral_original"
  batch_size: 10
  scaler_type: "pi-scale"
  img_size: 300
  test_size: 0.2
  val_size: 0.2
  num_workers: 2
  padding_mode: "edge"

model:
  model_name: "ViT"
  patch_size: 10
  in_channels: 3
  embed_size: 64
  depth: 2
  heads: 2
  mlp_dim: 128
  dropout: 0.1
  learning_rate: 1e-5
  embedding_type: "fourier"
  fourier_params:
    gridsize: 8
    addbias: true
    smooth_initialization: false

training:
  max_epochs: 30
